"""bleh

Revision ID: 461383e0c920
Revises: 
Create Date: 2022-08-08 12:06:04.667162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461383e0c920'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('game_title', sa.String(), nullable=True),
    sa.Column('game_genre', sa.String(), nullable=True),
    sa.Column('game_platform', sa.String(), nullable=True),
    sa.Column('game_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('review_score', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.String(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('games')
    # ### end Alembic commands ###
